# Generated by Django 4.2.16 on 2026-09-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(default=dict)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='streams.stream')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stream', 'timestamp'], name='ingestion_d_stream__3c90ca_idx')],
            },
        ),
    ]
