# Generated by Django 4.2.16 on 2026-10-02 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0004_add_retention_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STREAM_CREATED', 'Stream created'), ('STREAM_PAUSED', 'Stream paused'), ('STREAM_RESUMED', 'Stream resumed'), ('STREAM_DELETED', 'Stream deleted'), ('MEMBER_INVITED', 'Member invited'), ('MEMBER_ROLE_CHANGED', 'Member role changed'), ('MEMBER_REMOVED', 'Member removed'), ('ALERT_ACKNOWLEDGED', 'Alert acknowledged'), ('ALERT_RESOLVED', 'Alert resolved'), ('EXPORT_REQUESTED', 'Export requested'), ('LSTM_TRAINING_TRIGGERED', 'LSTM training triggered'), ('WEBHOOK_CREATED', 'Webhook created'), ('WEBHOOK_DELETED', 'Webhook deleted')], db_index=True, max_length=40)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='streams.stream')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events_as_target', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='streams.workspace')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='audit_audit_workspa_dd7fb9_idx'), models.Index(fields=['workspace', 'action'], name='audit_audit_workspa_9cc923_idx')],
            },
        ),
    ]
