# Generated by Django 4.2.16 on 2026-10-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('STREAM_CREATED', 'Stream created'), ('STREAM_PAUSED', 'Stream paused'), ('STREAM_RESUMED', 'Stream resumed'), ('STREAM_DELETED', 'Stream deleted'), ('MEMBER_INVITED', 'Member invited'), ('MEMBER_ROLE_CHANGED', 'Member role changed'), ('MEMBER_REMOVED', 'Member removed'), ('ALERT_ACKNOWLEDGED', 'Alert acknowledged'), ('ALERT_RESOLVED', 'Alert resolved'), ('EXPORT_REQUESTED', 'Export requested'), ('LSTM_TRAINING_TRIGGERED', 'LSTM training triggered'), ('WEBHOOK_CREATED', 'Webhook created'), ('WEBHOOK_DELETED', 'Webhook deleted'), ('ALERT_RULE_CREATED', 'Alert rule created'), ('ALERT_RULE_DELETED', 'Alert rule deleted')], db_index=True, max_length=40),
        ),
    ]
