# Generated by Django 4.2.16 on 2026-10-07 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0005_add_stream_rollup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('condition', models.CharField(choices=[('ABOVE', 'Value above threshold'), ('BELOW', 'Value below threshold'), ('CHANGE_PCT', 'Change exceeds % threshold')], max_length=20)),
                ('threshold', models.FloatField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='HIGH', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_fired', models.DateTimeField(blank=True, null=True)),
                ('cooldown_minutes', models.PositiveIntegerField(default=5, help_text='Minimum minutes between firings of this rule.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='streams.stream')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stream', 'is_active'], name='alerts_aler_stream__8dbe07_idx')],
            },
        ),
    ]
