# Generated by Django 4.2.16 on 2026-10-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('streams', '0004_add_retention_days'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_severity', models.CharField(default='HIGH', help_text='Only notify at or above this severity.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_url', models.URLField()),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_integration', to='streams.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PagerDutyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_severity', models.CharField(default='HIGH', help_text='Only notify at or above this severity.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routing_key', models.CharField(max_length=64)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagerduty_integration', to='streams.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SLACK', 'Slack'), ('PAGERDUTY', 'PagerDuty')], max_length=20)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Error'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('response_code', models.IntegerField(null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert', 'channel'], name='integration_alert_i_3cf66b_idx')],
            },
        ),
    ]
