# Generated by Django 4.2.16 on 2026-10-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0005_add_stream_rollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('annotation_type', models.CharField(choices=[('EVENT', 'Event'), ('MARKER', 'Marker'), ('REGION', 'Region')], default='EVENT', max_length=10)),
                ('color', models.CharField(choices=[('gray', 'Gray'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], default='blue', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('end_timestamp', models.DateTimeField(blank=True, help_text='Required for REGION type.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='streams.stream')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['stream', 'timestamp'], name='annotations_stream__b1cca6_idx')],
            },
        ),
    ]
