# Generated by Django 4.2.16 on 2026-09-29 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source_type', models.CharField(choices=[('SIMULATOR', 'IoT Simulator'), ('CSV', 'CSV Upload'), ('HTTP', 'HTTP Endpoint')], max_length=20)),
                ('source_config', models.JSONField(default=dict)),
                ('sampling_interval', models.PositiveIntegerField(default=5, help_text='seconds')),
                ('detector_type', models.CharField(choices=[('ZSCORE', 'Z-Score'), ('IQR', 'IQR'), ('LSTM', 'LSTM')], default='ZSCORE', max_length=20)),
                ('detector_config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ERROR', 'Error')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='streams.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
