# Generated by Django 4.2.16 on 2026-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_workspace_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='detector_type',
            field=models.CharField(choices=[('ZSCORE', 'Z-Score'), ('IQR', 'IQR'), ('LSTM', 'LSTM'), ('ENSEMBLE', 'Ensemble')], default='ZSCORE', max_length=20),
        ),
    ]
