# Generated by Django 4.2.16 on 2026-10-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_add_ensemble_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-delete DataPoints older than N days. Null = keep forever.', null=True),
        ),
    ]
