# Generated by Django 4.2.16 on 2026-10-07 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0004_add_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily')], max_length=10)),
                ('bucket_ts', models.DateTimeField(db_index=True, help_text='Start of the bucket, truncated to the period.')),
                ('count', models.PositiveIntegerField()),
                ('mean', models.FloatField()),
                ('std', models.FloatField()),
                ('min_val', models.FloatField()),
                ('max_val', models.FloatField()),
                ('p50', models.FloatField()),
                ('p95', models.FloatField()),
                ('p99', models.FloatField()),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='streams.stream')),
            ],
            options={
                'ordering': ['-bucket_ts'],
                'indexes': [models.Index(fields=['stream', 'period', 'bucket_ts'], name='streams_str_stream__2a6560_idx')],
                'unique_together': {('stream', 'period', 'bucket_ts')},
            },
        ),
    ]
