# Generated by Django 4.2.16 on 2026-10-08 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sharing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0005_add_stream_rollup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=sharing.models._new_token, max_length=36, unique=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('max_points', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_shares', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='streams.stream')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='sharing_das_token_a57807_idx')],
            },
        ),
    ]
